export type AuthUser = {
  id: string;
  email: string;
  firstName: string;
  lastName?: string;
  bio?: string;
  photoUrl?: string;
  organization?: string;
  mobileNo?: string;
  phoneNo?: string;
  country?: string;
  countryName?: string;
  state?: string;
  city?: string;
  address?: string;
  language?: string;
  languageName?: string;
  timeZone?: string;
  gender?: string;
  genderName?: string;
};
